version: 2
jobs:
  build:
    working_directory: /usr/src/dotenv
    docker:
      - image: nimlang/nim
    steps:
      - checkout
      - run:
          name: install dependencies
          command: nimble install -y
      - run:
          name: test
          command: nim c -r src/twitter.nim
  build_alpine:
    working_directory: /usr/src/dotenv
    docker:
      - image: nimlang/nim:alpine
    steps:
      - checkout
      - run:
          name: install dependencies
          command: nimble install -y
      - run:
          name: test
          command: nim c -r src/twitter.nim
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build_alpine
