version: 2
jobs:
  build:
    docker:
      - image: nimlang/nim
    steps:
      - run: echo 'export PATH=~/.nimble/bim:PATH' >> $BASH_ENV
      - checkout
      - restore_cache:
          key: nim-0000
      - save_cache:
          key: nim-0000
          paths:
            - .nimble
      - run: nimble build -y
      - run: nim c -r src/twitter.nim
