on:
  push:
    branches:
      - image-upload
  pull_request:
    branches: 
      - master
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@image-upload
      - uses: jiro4989/setup-nim-action@v1.0.5
      - run: nimble build -Y
      - run: nimble test -Y
